### ISSUE TITLE
Why does nginx container need access to python files? 

### ISSUE THREAD

**Issue by amjith** [AndrewRPorter/flask-nginx-tutorial#1]
In [docker-compose.yml](https://github.com/AndrewRPorter/flask-nginx-tutorial/blob/master/docker-compose.yml#L8), you're mapping the current directory to /var/www folder, why? 

Wouldn't nginx just need access to its config file and whatever static files it'll be serving?

**Comment by AndrewRPorter** [comment]
Thank you, fixed.
