### ISSUE TITLE
localhost not resolving in browser

### ISSUE THREAD

**Issue by CianSteenkamp96** [AndrewRPorter/flask-nginx-tutorial#2]
Hey Andrew

I downloaded your code and ran `sudo docker-compose up --build`. The output in my terminal was the same as in your video.

However, when I go to my browser and try to navigate to `http://localhost/` the page just keeps loading indefinitely...

I am running a **Ubuntu 18.04 host machine**.

Do you know why this could be the case? 

Thank You

**Comment by AndrewRPorter** [comment]
What is the output?
